# Generated by Django 4.0.4 on 2022-05-23 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_alter_advertisement_options_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='favorites',
        ),
        migrations.AddField(
            model_name='favorites',
            name='favorites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisements.advertisement'),
        ),
    ]
